package com.example.turapp.utils.helperFiles

const val REQUEST_CODE_LOCATION_PERMISSION = 123

const val REQUEST_CODE_CAMERA_PERMISSION = 2

const val REQUEST_CODE_CAMERA_AND_LOCATION = 0

const val CHANNEL_ID = "location"

const val NAVIGATION_ARGUMENT_SAVING_TYPE = "NAVIGATION_ARGUMENT_SAVING_TYPE"




