package com.example.turapp.utils.helperFiles

const val REQUEST_CODE_LOCATION_PERMISSION = 123

const val REQUEST_CODE_CAMERA_PERMISSION = 2

const val STARTING_POINT = "STARTING_POINT"

const val END_POINT = "END_PONT"

const val CHANNEL_ID = "location"

const val NAVIGATION_ARGUMENT_SAVING_TYPE_TRACKING = "NAVIGATION_ARGUMENT_SAVING_TYPE_TRACKING"

const val NAVIGATION_ARGUMENT_SAVING_TYPE_SNAPSHOT = "NAVIGATION_ARGUMENT_SAVING_TYPE_SNAPSHOT"

const val NAVIGATION_ARGUMENT_SAVING_TYPE_POI = "NAVIGATION_ARGUMENT_SAVING_TYPE_POI"

const val NAVIGATION_ARGUMENT_SAVING_TYPE = "NAVIGATION_ARGUMENT_SAVING_TYPE"




