package com.example.turapp.repository.trackingDb.entities

const val TYPE_POI = "TYPE_POI"

const val TYPE_TRACKING = "TYPE_TRACKING"

const val TYPE_SNAPSHOT = "TYPE_SNAPSHOT"

const val TRACKING_STARTING_POINT = "TRACKING_STARTING_POINT"

const val TRACKING_PAUSE_POINT = "TRACKING_PAUSE_POINT"

const val TRACKING_RESUME_POINT = "TRACKING_RESUME_POINT"


const val TRACKING_END_POINT = "TRACKING_END_POINT"